# Generated by Django 4.2 on 2026-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_prescription_id_alter_testresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test_results/'),
        ),
    ]
