# Generated by Django 6.0.3 on 2026-03-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_amount_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_intent_id',
        ),
    ]
