# Generated by Django 6.0.3 on 2026-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
