# Generated by Django 4.2 on 2026-03-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clinic_city_clinic_pincode_clinic_website_lab_city_and_more'),
        ('appointments', '0008_availability_appointmentslot_appointment_slot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='DoctorAvailability',
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
        migrations.AlterModelTable(
            name='doctoravailability',
            table='doctor_availability',
        ),
    ]
