# Generated by Django 4.2 on 2026-03-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
        ('appointments', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.lab')),
            ],
            options={
                'db_table': 'lab_holidays',
                'unique_together': {('lab', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LabAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(default=15)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.lab')),
            ],
            options={
                'db_table': 'lab_availability',
                'unique_together': {('lab', 'day_of_week')},
            },
        ),
    ]
