# Generated by Django 4.2 on 2026-04-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_labholiday_labavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PAY_AT_CLINIC', 'Pay at Clinic')], default='ONLINE', max_length=50),
        ),
    ]
