# Generated by Django 4.2 on 2026-04-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_lab_home_collection_available_and_more'),
        ('appointments', '0012_appointment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_home_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='users.labtest'),
        ),
    ]
