# Generated by Django 4.2 on 2026-04-29 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_testrequest'),
        ('appointments', '0013_appointment_is_home_collection_appointment_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.testrequest'),
        ),
    ]
