# Generated by Django 4.2 on 2026-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_appointment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
