# Generated by Django 4.2 on 2026-05-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_lab_consultation_fee'),
        ('appointments', '0016_appointment_reschedule_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicScheduleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('action_type', models.CharField(choices=[('BLOCK', 'Block Slot'), ('BREAK', 'Break Time'), ('ADJUST', 'Adjust Timing')], max_length=10)),
                ('new_duration', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_actions', to='users.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_actions', to='users.doctor')),
            ],
            options={
                'db_table': 'clinic_schedule_actions',
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='users.doctor')),
            ],
            options={
                'db_table': 'doctor_leaves',
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reschedule_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled_at',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked'), ('BREAK', 'Break')], default='AVAILABLE', max_length=10),
        ),
        migrations.DeleteModel(
            name='LabHoliday',
        ),
    ]
