# Generated by Django 4.2 on 2026-05-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_lab_consultation_fee'),
        ('appointments', '0017_clinicscheduleaction_doctorleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(default='Break', max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='users.doctor')),
            ],
            options={
                'db_table': 'doctor_breaks',
            },
        ),
        migrations.CreateModel(
            name='DoctorHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.doctor')),
            ],
            options={
                'db_table': 'doctor_holidays',
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LabHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.lab')),
            ],
            options={
                'db_table': 'lab_holidays',
                'unique_together': {('lab', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorleave',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='status',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ClinicScheduleAction',
        ),
        migrations.DeleteModel(
            name='DoctorLeave',
        ),
    ]
