# Generated by Django 4.2 on 2026-05-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_lab_consultation_fee'),
        ('appointments', '0018_doctorbreak_doctorholiday_labholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='users.doctor')),
            ],
            options={
                'db_table': 'doctor_leaves',
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorholiday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorholiday',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='blocked_reason',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DoctorBreak',
        ),
        migrations.DeleteModel(
            name='DoctorHoliday',
        ),
    ]
