# Generated by Django 4.2 on 2026-05-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_doctorleave_alter_doctorholiday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
