# Generated by Django 4.2 on 2026-05-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_lab_consultation_fee'),
        ('appointments', '0020_doctoravailability_break_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='is_break',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='break_start',
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='doctorleave',
            table=None,
        ),
        migrations.CreateModel(
            name='DoctorBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='users.doctor')),
            ],
        ),
    ]
