# Generated by Django 6.0.3 on 2026-03-16 18:32

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_clinic_address_alter_clinic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('clinic', 'Clinic'), ('lab', 'Lab')], max_length=10)),
                ('entity_id', models.IntegerField()),
                ('document_type', models.CharField(choices=[('registration_cert', 'Registration Certificate'), ('medical_license', 'Medical License'), ('address_proof', 'Address Proof'), ('identity_proof', 'Identity Proof'), ('lab_license', 'Lab License'), ('lab_photo', 'Lab Photo'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to=users.models.verification_doc_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
