# Generated by Django 4.2 on 2026-04-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional advance payment amount required', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='payment_type',
            field=models.CharField(choices=[('PAY_AT_CLINIC', 'Pay at Clinic/Lab'), ('ONLINE', 'Online Payment'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional advance payment amount required', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lab',
            name='payment_type',
            field=models.CharField(choices=[('PAY_AT_CLINIC', 'Pay at Clinic/Lab'), ('ONLINE', 'Online Payment'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
    ]
