# Generated by Django 4.2 on 2026-04-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clinic_advance_payment_clinic_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='target_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.lab'),
        ),
    ]
