# Generated by Django 4.2 on 2026-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_testrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
